repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
        exclude: ^examples/.* # Regex pattern to exclude submodule directory
      - id: terraform_docs # Update our output, if updates it will force a failure which is good
        args:
          - "--args=-c .config/.terraform-docs.yml"
      - id: terraform_docs # Verify out output is up to date, sometimes the update fails
        always_run: true
        args:
          - "--args=--output-check=true"
      - id: terraform_tflint
        exclude: ^examples/.* # Regex pattern to exclude submodule directory
        args:
          - "--args=--only=terraform_deprecated_interpolation"
          - "--args=--only=terraform_deprecated_index"
          - "--args=--only=terraform_unused_declarations"
          - "--args=--only=terraform_comment_syntax"
          - "--args=--only=terraform_documented_outputs"
          - "--args=--only=terraform_documented_variables"
          - "--args=--only=terraform_typed_variables"
          - "--args=--only=terraform_module_pinned_source"
          - "--args=--only=terraform_naming_convention"
          - "--args=--only=terraform_required_version"
          - "--args=--only=terraform_required_providers"
          - "--args=--only=terraform_workspace_remote"
  # Native Git PreCommit Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
  #GitLeaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  #Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
