name: Run pre-commit on push

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wesleykirkland/docker-terraform:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git safe directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run pre-commit
        run: |
          pre-commit run --all-files
